project:
  type: website
  output-dir: docs

website:
  title: "Da-Yea Song"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - example analysis.qmd
format:
  html:
    theme: Journal
    stylesheets: ["styles.css"]

editor: visual

